-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- USERS TABLE
create table if not exists users (
  id text primary key,
  secure_id text unique not null,
  public_key text not null,
  identity_key text,
  encrypted_private_key text,
  username text unique not null,
  profile_image text,
  online boolean default false,
  socket_id text,
  device_id text,
  login_token text,
  password_hash text,
  signed_pre_key_id integer,
  signed_pre_key text,
  signed_pre_key_signature text,
  supports_advanced boolean default false,
  created_at bigint default extract(epoch from now())
);

-- CHATS TABLE
create table if not exists chats (
  id text primary key,
  created_at bigint default extract(epoch from now())
);

-- CHAT PARTICIPANTS TABLE
create table if not exists chat_participants (
  chat_id text not null references chats(id) on delete cascade,
  user_id text not null references users(id) on delete cascade,
  muted boolean default false,
  pinned boolean default false,
  primary key (chat_id, user_id)
);

-- MESSAGES TABLE
create table if not exists messages (
  id text primary key,
  chat_id text not null references chats(id) on delete cascade,
  from_id text not null references users(id) on delete cascade,
  encrypted_content text,
  type text default 'text',
  media_url text,
  timestamp bigint,
  sender_plaintext text,
  status text default 'sent',
  reply_to_id text,
  created_at bigint default extract(epoch from now())
);

-- MESSAGE READS TABLE
create table if not exists message_reads (
  message_id text not null references messages(id) on delete cascade,
  reader_id text not null references users(id) on delete cascade,
  read_at bigint default extract(epoch from now()),
  primary key (message_id, reader_id)
);

-- SUBSCRIPTIONS TABLE (Web Push)
create table if not exists subscriptions (
  id bigint generated by default as identity primary key,
  user_id text not null references users(id) on delete cascade,
  endpoint text unique not null,
  keys_p256dh text,
  keys_auth text,
  created_at bigint default extract(epoch from now())
);

-- INDEXES
create index if not exists idx_messages_chat on messages(chat_id);
create index if not exists idx_chat_participants_user on chat_participants(user_id);
create index if not exists idx_users_username on users(username);
create index if not exists idx_users_device on users(device_id);
create index if not exists idx_users_secure_id on users(secure_id);
create index if not exists idx_users_token on users(login_token);

-- FUNCTIONS (RPC)

-- Get or Create Chat between two users
create or replace function get_or_create_chat(p_user1 text, p_user2 text)
returns text
language plpgsql
security definer
as $$
declare
  v_chat_id text;
begin
  -- Check if chat exists
  select cp1.chat_id into v_chat_id
  from chat_participants cp1
  join chat_participants cp2 on cp1.chat_id = cp2.chat_id
  where cp1.user_id = p_user1 and cp2.user_id = p_user2
  limit 1;

  return v_chat_id;
end;
$$;

-- Get User Chats with details
create or replace function get_user_chats(p_user_id text)
returns table (
  chat_id text,
  friend_id text,
  friend_name text,
  friend_key text,
  friend_identity_key text,
  friend_image text,
  muted boolean,
  pinned boolean,
  last_message jsonb
)
language plpgsql
security definer
as $$
begin
  return query
  select 
    c.id as chat_id,
    u.id as friend_id,
    u.username as friend_name,
    u.public_key as friend_key,
    u.identity_key as friend_identity_key,
    u.profile_image as friend_image,
    cp.muted,
    cp.pinned,
    (
      select to_jsonb(m) from messages m 
      where m.chat_id = c.id 
      order by m.timestamp desc limit 1
    ) as last_message
  from chat_participants cp
  join chats c on cp.chat_id = c.id
  join chat_participants cp2 on c.id = cp2.chat_id and cp2.user_id != p_user_id
  join users u on cp2.user_id = u.id
  where cp.user_id = p_user_id;
end;
$$;
