-- Run this in your Supabase SQL Editor to update the schema
-- This adds missing columns needed for the latest version of Vibe

-- Add encrypted_private_key for key sync
ALTER TABLE users ADD COLUMN IF NOT EXISTS encrypted_private_key text;

-- Add fields for Advanced Encryption (PreKeys)
ALTER TABLE users ADD COLUMN IF NOT EXISTS signed_pre_key_id integer;
ALTER TABLE users ADD COLUMN IF NOT EXISTS signed_pre_key text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS signed_pre_key_signature text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS supports_advanced boolean default false;

-- Add profile image if missing
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_image text;

-- Add subscription support if missing
CREATE TABLE IF NOT EXISTS subscriptions (
  id bigint generated by default as identity primary key,
  user_id text not null references users(id) on delete cascade,
  endpoint text unique not null,
  keys_p256dh text,
  keys_auth text,
  created_at bigint default extract(epoch from now())
);
